package problems.utils;

public enum AlphabeticalOrderState {
  IN_ALPHABETICAL_ORDER,
  IN_REVERSE_ALPHABETICAL_ORDER,
  IN_BOTH_ALPHABETICAL_AND_REVERSE_ALPHABETICAL_ORDER,
  IN_NEITHER_ALPHABETICAL_NOR_REVERSE_ALPHABETICAL_ORDER;
}
